#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required
group: edge

################
# build matrix #
################

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-9
        - CXXFLAGS=-std=c++1z
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9', 'ninja-build']

    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-7
        - CXXFLAGS=-std=c++1z
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'ninja-build']

################
# build script #
################

script:
  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then
      export CXX=${COMPILER};
    fi

  # compile
  - mkdir -p build && cd build
  - cmake .. -GNinja && cmake --build . --config Release
  - cd ..
